export const URL = "https://api.themoviedb.org/3/";
export const APIKEY = "9a2955322d7a5fbef5b01d4e52abc0ff";

export const FILTER = {
    ALLGENRES: 'ALLGENRES',
    ALLGENRES1: 'ALLGENRES1',
    CONTENTIS: 'CONTENTIS',
    SEARCHMOVIE: 'SEARCHMOVIE',
    SEARCHTV: 'SEARCHTV',
    SEARCH_PEOPLE: 'SEARCH_PEOPLE'
}

export const MOVIER = {
    ERROR: 'ERROR',
    NOWPLAYING: 'NOWPLAYING',
    TOPBOXOFFICE: 'TOPBOXOFFICE',
    UPCOMING: 'UPCOMING',
    POPULAR: 'POPULAR',
    MOVIE_DETAILS: 'MOVIE_DETAILS',
    OTHERDETAILS: 'OTHERDETAILS',
    CAST: 'CAST',
    REBURE: 'REBURE',
    CREW: 'CREW',
    SIMILARMOV: 'SIMILARMOV',
    GENRES: 'GENRES',
    OVER: 'OVER',
    DISCOVERNOW: 'DISCOVERNOW',
}

export const PEEPS = {
    PEOPLE_DETAIL: 'PEOPLE_DETAIL',
    PERS_DETAIL: 'PERS_DETAIL',
    PERS_IMG: 'PERS_IMG',
    WORKIN: 'WORKIN',
    WORKINTV: 'WORKINTV',
    POPULAR_PEOPLE: 'POPULAR_PEOPLE',
}

export const TVS = {
    SIMILARTV: 'SIMILARTV',
    CASTTV: 'CASTTV',
    RUNTV: 'RUNTV',
    TVDETAILS: 'TVDETAILS',
    TVIMG: 'TVIMG',
    GETRAT: 'GETRAT',
    GETFIRSTAIR: 'GETFIRSTAIR',
    GETLASTAIR: 'GETLASTAIR',
    GETNET: 'GETNET',
    GETSHOWTYPE: 'GETSHOWTYPE',
    GETSHOWSTAT: 'GETSHOWSTAT',
    GETCREATOR: 'GETCREATOR',
    TOPRATEDTV: 'TOPRATEDTV',
    TVSEASON: 'TVSEASON',
    AIRING_TODAY: 'AIRING_TODAY',
    POPULARTV: 'POPULARTV',
}